Repository FOSS-Tech/Git-Github-Session, pull requests merged in 2022-10, with the labels that each got.

#42 apurvalodha23.md
  apurvalodha23.md
Labels: enhancement, good-first-pr

#54 Create Shashank-Menaria.md
  contributors-list/Shashank-Menaria.md
Labels: good-first-pr

#52 Add_Vednshi_Pareek
  contributors-list/VedanshiPareek.md
Labels: good first PR

#51 hsoni6954.md
  contributors-list/harshit-paneri.md
  contributors-list/hsoni6954.md
Labels: good first PR

#48 addeddivyashaktpal.md
  contributors-list/divyashaktipal.md
Labels: good first PR

#50 Update README.md
  README.md
Labels: good first PR

#44 add_Mitvesh
  contributors-list/Mitesh.md
Labels: good first PR

#45 Create Garvita_jain.md
  contributors-list/Garvita_jain.md
Labels: good first PR

#43 added_name
  contributors-list/RIYAJAIN21.md
Labels: good first PR

#40 Create zemanisteragues.md
  contributors-list/zemanisteragues.md
Labels: good first PR

#1 added priyanshuarora595.md
  contributors-list/Manas-tech.md
Labels: good first PR

#39 Create Akshita Kumawat. md
  contributors-list/Akshita Kumawat. md
Labels: good first PR

#38 Create dsd.md
  contributors-list/dsd.md
Labels: good first PR

#2 added avani07joshi.md
  contributors-list/avani07joshi.md
Labels: good first PR

#3 added kanishka-parmar.md
  kanishka-parmar.md
Labels: good first PR

#36 add_Pushkar-Gameti
  contributors-list/Pushkar-Gameti.md
Labels: good first PR

#34 Create Lavishaa.md
  contributors-list/Lavishaa.md
Labels: good first PR

#4 added Nisha-lohar.md
  contributors-list/Nisha-lohar.md
Labels: good first issue

#5 changed the name Vyomji.md
  contributors-list/Vyomji.md
Labels: good first PR

#6 added jaydeepdangi.md
  contributors-list/jaydeepdangi.md
Labels: good first PR

#8 added AasthaDakhera.md
  contributors-list/AasthaDakhera.md
Labels: good first PR

#10 added Yashgoswami14.md
  contributors-list/Yashgoswami14.md
Labels: good first PR

#11 added manas2003.md
  contributors-list/manas2003.md
Labels: good first PR

#12 Create khushigahlot.md
  contributors-list/khushigahlot.md
Labels: good first PR

#13 added vaibhavsoni18.md
  contributors-list/vaibhavsoni18.md
Labels: good first PR

#14 added Roshni568
  contributors-list/Roshni568.MD
Labels: good first PR

#25 added lalita2206.md
  contributors-list/lalita2206.md
Labels: good first PR

#30 add_divyanshu212
  contributors-list/divyanshu212
Labels: good first PR

#26 added Lakshya-bhavsar
  contributors-list/Lakshya-bhavsar.md
Labels: good first PR

#24 added_pranjal1902.md
  contributors-list/pranjal1902.md
Labels: good first PR

#21 added tanishakumawat.md
  contributors-list/tanishakumawat.md
Labels: good first PR

#23 added MayankMaliwal.md
  contributors-list/MayankMaliwal.md
Labels: good first PR

#16 Create Himanshi Prajapat
  contributors-list/Himanshi Prajapat
Labels: good first PR

#20 added Rupalsoni123.md
  contributors-list/Rupalsoni123.md
Labels: good first PR

#18 Create vaibhav25garg.md
  contributors-list/vaibhav25garg.md
Labels: good first PR

#17 addedUtkarshbajpai07
  contributors-list/Utkarshbajpai07.md
Labels: good first PR

#7 added nehal1123.md
  contributors-list/nehal1123.md
Labels: good first PR

#59 diksha.md
  contributors-list/diksha-agarwal
Labels: good first PR

#60 added kanishka-parmar.md
  contributors-list/kanishka-parmar.md
Labels: good first PR
